title = "陈 sir 的博客"
baseURL = "/"
languageCode = "zh-CN"
theme = "hugoclarity"

DefaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.zh-cn]
    title = "陈 sir 的博客"
    weight = 1
    contentDir = "content/zh"
#  [languages.en]
#    title = "chen sir's blog "
#    weight = 2
#    contentDir = "content/en"



[[menu.main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[menu.main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/yudar1024"
[[menu.main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/"
