title = "陈 sir 的博客"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.zh]
    title = "陈 sir 的博客"
    weight = 1
    contentDir = "content/zh"
  [languages.en]
    title = "chen sir's blog "
    weight = 2
    contentDir = "content/en"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/"
  twitter = "https://twitter.com/"
  instagram = ""
  youtube = ""
  github = "https://github.com/yudar1024"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5
